#!/bin/bash

#get data
wget http://files.grouplens.org/datasets/movielens/ml-1m.zip

unzip ml-1m.zip

#set separator to comma, get only first three columns and drom time stamp
cat ml-1m/ratings.dat | sed 's/::/,/g' | cut -f1-3 -d, > ratings.csv

#put input data to hadoop distributed file system
hadoop fs -put ratings.csv /ratings.csv

#run mahout job
mahout recommenditembased --input /ratings.csv --output recommendations --numRecommendations 10 --outputPathForSimilarityMatrix similarity-matrix --similarityClassname SIMILARITY_COSINE

#check results
hadoop fs -ls recommendations
hadoop fs -cat recommendations/part-r-00000 | head

#download python network, webservice and redis libraries
sudo easy_install twisted
sudo easy_install klein
sudo easy_install redis

#start reddis server
wget http://download.redis.io/releases/redis-2.8.7.tar.gz
tar xzf redis-2.8.7.tar.gz
cd redis-2.8.7
make
./src/redis-server &